---
- name: validate states on EOS devices
  hosts: DC1
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: validate states on EOS devices
      import_role:
        name: arista.avd.eos_validate_state
      vars:
        fabric_name: "DC"
        root_dir: '../DC-information'
        root_dir: 'DC-information'
        structured_dir: 'intended/structured_configs' 
