name: 'Dev Runner'

on:
  push:
#    branches-ignore:
#      - main

# on:
#   push:

jobs:
  avd-dev-deployment:
    runs-on: [self-hosted, dev]
    # test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Build Configurations
        run: ansible-playbook -i inventory.yml build.yml -vvvv

      - name: Deploy Configuration to CVP
        run: ansible-playbook -i inventory.yml deploy-cvp.yml -vvvv

      - run: sleep 10

      - name: Validate connectivity
        run: ansible-playbook -i inventory.yml fabric-validation.yml -vvvv
#
#      
#      
#      - name: Run AVD EOS Validate State Playbook against ACT
#        run: ansible-playbook -i inventory/inventory.yml playbooks/fabric-validation.yml --skip-tags "ntp,reload_cause,mlag,optional"
#        #run: foo.py 
#
#      - name: Upload verification reports to github
#        uses: actions/upload-artifact@master
#        with:
#          name: ValidationReport
#          path: DC-information/reports/

